- .github/.codecov.yml
- .github/workflows/analysis-coverage.yml
- nc_py_api/preferences.py
- nc_py_api/users_statuses.py
- pyproject.toml
- tests/appconfig_preferences_ex_test.py
- tests/apps_test.py
- tests/gfixture.py
- tests/groups_test.py
- tests/logs_test.py
- tests/preferences_test.py
- tests/users_statuses_test.py
- tests/users_test.py
Tests adjusted to not run on Oracle without AppEcosystem
> fixed tests with Oracle

- .github/workflows/publish.yml
- CHANGELOG.md
- nc_py_api/_version.py
> test publish ci [publish]

- tests/appconfig_preferences_ex_test.py
enabled empty value test in **test_cfg_ex_set_delete**
> enabled appcfg tests for empty values

- tests/apps_test.py
- tests/groups_test.py
- tests/users_test.py
Some tests that should run, are skipped, due to yesterday PR(Oracle)
These fixes it
> fixed tests not to skip

- .readthedocs.yml
- nc_py_api/__init__.py
- nc_py_api/exceptions.py
- nc_py_api/users_groups.py
- nc_py_api/users_statuses.py
- tests/groups_test.py
- tests/misc_test.py
- tests/users_statuses_test.py
Minimum coverage for this project should be at least 95%
> +tests, increased coverage

- .github/workflows/analysis-coverage.yml
- nc_py_api/_session.py
- nc_py_api/nextcloud.py
- pyproject.toml
- tests/_install.py
- tests/nc_app_test.py
> +tests as application

- .github/workflows/analysis-coverage.yml
- CHANGELOG.md
- Makefile
- nc_py_api/_session.py
- nc_py_api/integration_fastapi.py
- nc_py_api/nextcloud.py
- tests/_install.py
In final deploy concept we removed `expose` parameter to make it simpler.
> for next AppEcosystem update

- CHANGELOG.md
- nc_py_api/apps.py
- tests/apps_test.py
Today's update of App Ecosystem
> added ex_app_get_list, ex_app_get_info

- Makefile
- docs/benchmarks/AppEcosystem.rst
- docs/index.rst
From this stage every new feature should be documented from start, and I'll start documented what is already done and how to use it.
> start writing docs

- nc_py_api/files.py
- tests/files_test.py
Forget to add it, but here it is
> fixed: download2stream, upload_stream can accept paths.

- .github/workflows/analysis-coverage.yml
> hope final changes for deploy

- .github/workflows/analysis-coverage.yml
- nc_py_api/_version.py
- nc_py_api/appconfig_preferences_ex.py
- nc_py_api/misc.py
- nc_py_api/theming.py
- nc_py_api/users_status.py
- scripts/dev_register.sh
- tests/_app_security_checks.py
- tests/_install.py
- tests/_install_wait.py
- tests/files_test.py
- tests/misc_test.py
- tests/theming_test.py
Finishing all tests for all stuff that is currently implemented
> improving tests

- CHANGELOG.md
- docs/Options.rst
- docs/reference/Files.rst
- nc_py_api/_session.py
- nc_py_api/files.py
- nc_py_api/files_sharing.py
- nc_py_api/options.py
- tests/files_test.py
- tests/ui_file_actions_test.py
Tomorrow will rewrite tests and `FileAPI` is in RC stage.
> brilliant reworked `FileAPI`

- tests/data/nc_pass_confirm.patch
- tests/misc_test.py
- tests/z_special.py
- tests/z_special_test.py
We should test "password confirmation" stuff for Nextcloud Client mode
> special test

- nc_py_api/apps.py
- nc_py_api/files.py
- nc_py_api/files_defs.py
- nc_py_api/files_sharing.py
- nc_py_api/nextcloud.py
- nc_py_api/preferences.py
- nc_py_api/theming.py
- nc_py_api/ui_files_actions_menu.py
- nc_py_api/users.py
- nc_py_api/users_groups.py
- nc_py_api/users_notifications.py
- nc_py_api/users_status.py
- nc_py_api/users_weather.py
- pyproject.toml
> added ruff's `D202` check

- .github/workflows/analysis-coverage.yml
- .gitignore
- .run/to_gif.run.xml
- examples/as_app/to_gif/Dockerfile
- examples/as_app/to_gif/Makefile
- examples/as_app/to_gif/main.py
- scripts/dev_register.sh
1. Added `run` configuration for PyCharm to more easy register development manual deploy version.
2. Added small `Makefile` with basic commands that will help easy test it.
3. As `nc_py_api` now are already hosted on `pypi` made a normal requirements.txt
4. Added use of notification, and FastAPI `background_task`
@andrey18106 after you test it, we can merge this.
> updating `to_gif` example

- .github/workflows/analysis-coverage.yml
As this was merged, we do not need Authentication patch anymore for Nextcloud core.
nextcloud/server/pull/39655
> removed AE auth patch for NC `master` branch, updated versions

- .github/workflows/analysis-coverage.yml
- CHANGELOG.md
- docs/Options.rst
- nc_py_api/__init__.py
- nc_py_api/_version.py
- nc_py_api/options.py
- tests/options_test.py
Subj, implemented some tests for `options.py` stuff.
> fixed `options` + tests for that.

- .github/workflows/analysis-coverage.yml
- CHANGELOG.md
- nc_py_api/files/sharing.py
- tests/files_sharing_test.py
Pending and deleted shares, do not work on my local setup, so no `True` tests for them currently.
> Sharing API + tests

- nc_py_api/_session.py
- pyproject.toml
- tests/_install_wait.py
- tests/files_sharing_test.py
- tests/files_test.py
- tests/gfixture.py
- tests/logs_test.py
- tests/options_test.py
- tests/users_groups_test.py
- tests/users_test.py
- tests/z_special_test.py
> added ruff `SIM` check

- .run/_app_security_checks.run.xml
- .run/register.run.xml
- nc_py_api/_session.py
- nc_py_api/_version.py
- tests/_app_security_checks.py
Reject requests with different from ours `EX-APP-VERSION`
> added EX-APP-VERSION handling

- CHANGELOG.md
- docs/conf.py
- nc_py_api/_session.py
- nc_py_api/files/files.py
- nc_py_api/nextcloud.py
- pyproject.toml
- tests/files_test.py
- tests/misc_test.py
This will allow to implement Talk API, as we need `X-Nextcloud-Talk-Hash` and `X-Nextcloud-Talk-Modified-Before` headers.
> added `Nextcloud.response_headers` property

- .github/workflows/analysis-coverage.yml
- .run/to_gif.run.xml
- CHANGELOG.md
- examples/COPYING
- examples/as_app/skeleton/Dockerfile
- examples/as_app/skeleton/Makefile
- examples/as_app/skeleton/appinfo/info.xml
- examples/as_app/skeleton/requirements.txt
- examples/as_app/skeleton/src/main.py
- examples/as_app/to_gif/Makefile
- examples/as_app/to_gif/appinfo/info.xml
- examples/as_app/to_gif/src/main.py
- nc_py_api/ex_app/__init__.py
- nc_py_api/ex_app/defs.py
- nc_py_api/ex_app/integration_fastapi.py
- nc_py_api/ex_app/uvicorn_fastapi.py
- nc_py_api/talk.py
- scripts/dev_register.sh
- tests/_install.py
- tests/_install_only_enabled_handler.py
CI will fail, waiting for AppEcosystem update
> reworked app-scopes definition

- docs/reference/Files/Files.rst
- docs/reference/Files/Shares.rst
- examples/as_app/skeleton/requirements.txt
- examples/as_app/to_gif/Makefile
- examples/as_app/to_gif/requirements.txt
- examples/as_app/to_gif/src/main.py
- nc_py_api/__init__.py
- nc_py_api/ex_app/ui/files.py
- nc_py_api/files/__init__.py
- nc_py_api/files/sharing.py
- tests/files_sharing_test.py
- tests/ui_files_test.py
```python3
def convert_video_to_gif(input_file: FsNode, nc: NextcloudApp):
save_path = path.splitext(input_file.user_path)[0] + ".gif"
pass
@APP.post("/video_to_gif")
async def video_to_gif(
file: UiFileActionHandlerInfo,
nc: Annotated[NextcloudApp, Depends(nc_app)],
background_tasks: BackgroundTasks,
):
background_tasks.add_task(convert_video_to_gif, file.actionFile.to_fs_node(), nc)
return Response()
```
Allowing to create ``FsNode`` from ``UiFileActionHandlerInfo``.
> UiActionFileInfo: added `to_fs_node` method.

- docs/conf.py
- docs/reference/ExApp.rst
- docs/reference/Session.rst
- nc_py_api/ex_app/defs.py
- nc_py_api/ex_app/ui/files.py
- nc_py_api/ex_app/ui/ui.py
- nc_py_api/nextcloud.py
- pyproject.toml
Nothing fixed, nothing important added, just some additional documentation with the help of sphinx.
> small docs update, still many work to do remain

- CHANGELOG.md
- docs/FirstSteps.rst
- docs/reference/Exceptions.rst
- nc_py_api/__init__.py
- nc_py_api/_exceptions.py
- nc_py_api/_misc.py
- nc_py_api/files/sharing.py
- nc_py_api/users/status.py
- nc_py_api/users/weather.py
- tests/misc_test.py
Allows this:
```python3
check_capabilities("user_status.enabled")
```
Needed for **Talk**, as it provides a very big amount of `capabilities`, need a clean way to check for them.
> extend `check_capabilities`

- .github/workflows/analysis-coverage.yml
- nc_py_api/options.py
- pyproject.toml
- tests/options_test.py
Was incorrect handling, as values in environment variables are strings.
> fixed bug when `options.NPA_NC_CERT=False`

- .github/workflows/analysis-coverage.yml
- examples/as_app/skeleton/requirements.txt
- examples/as_app/to_gif/Makefile
- examples/as_app/to_gif/appinfo/info.xml
- examples/as_app/to_gif/requirements.txt
- examples/as_app/to_gif/src/main.py
- scripts/dev_register.sh
- tests/talk_test.py
From now as we became closer to first Beta, we replace numerical values of API scope group to names, as they will be in release.
> replaced numerical values of API Scopes by names

- docs/NextcloudApp.rst
- examples/as_app/to_gif/appinfo/info.xml
- nc_py_api/files/__init__.py
Still missing chapters about logs and notifications.
And chapter about files is incomplete.
> + two chapters in docs for NcApp

- CHANGELOG.md
- nc_py_api/ex_app/ui/files.py
- nc_py_api/files/__init__.py
- nc_py_api/files/files.py
- tests/actual_tests/files_test.py
- tests/actual_tests/ui_files_test.py
Now devs can easy check mimetype of a file 👍
> Added `FsNode.info.mimetype`

- .github/workflows/analysis-coverage.yml
- .github/workflows/docs-check.yml
- .github/workflows/docs.yml
- .github/workflows/publish.yml
Little update, before new iteration
> updated NC versions, pinned checkout action to number.

- .github/workflows/analysis-coverage.yml
- tests/actual_tests/calendar_test.py
Hope this will fix fail tests in AppAPI repo related to calendar and `nc_py_api`
> improved calendar test

- CHANGELOG.md
- docs/conf.py
- docs/resources/css/styles.css
> docs: fixed missed CSS

- scripts/ci_register.sh
- scripts/dev_register.sh
Adjustments to nc_py_api API if needed will come later, this PR should make pass test here: 
https://github.com/cloud-py-api/app_api/pull/128
> added "--wait-finish" for occ app_api:app:register (AppAPI 1.3+)

- Makefile
- README.md
- docs/Makefile
- docs/NextcloudApp.rst
- docs/NextcloudTalkBot.rst
- docs/NextcloudUiApp.rst
- docs/index.rst
During the release there was a deadline and there was no time for documentation - fixing it now.
> docs for ExApp UI

- CHANGELOG.md
- README.md
- docs/NextcloudTalkBot.rst
- examples/as_app/talk_bot/lib/main.py
- pyproject.toml
- tests/_app_security_checks.py
- tests/_talk_bot.py
- tests/_talk_bot_async.py
* I forgot why there was a dependency on "requests" package, so removed it, as we use "httpx" package.
> removed `requests` package

- nc_py_api/_session.py
- nc_py_api/files/files.py
Just refactoring, remove redundant code.
> use existing `_session.download2fp` method [refactor]

- .github/workflows/analysis-coverage.yml
- nc_py_api/talk_bot.py
> app_api-2.0: fixed forgot about slash removal

- docs/reference/Files/Shares.rst
- nc_py_api/_preferences_ex.py
- nc_py_api/_talk_api.py
- nc_py_api/ex_app/providers/speech_to_text.py
- nc_py_api/ex_app/providers/text_processing.py
- nc_py_api/ex_app/providers/translations.py
- nc_py_api/ex_app/ui/files_actions.py
- nc_py_api/ex_app/ui/resources.py
- nc_py_api/ex_app/ui/settings.py
- nc_py_api/ex_app/ui/top_menu.py
- nc_py_api/files/files.py
- nc_py_api/files/sharing.py
Maybe this will help people to see how they can access class functionality..
Related: #223
> Added comment to classes: "avalaible as XXX.path"

- tests/actual_tests/files_test.py
- tests/actual_tests/user_status_test.py
- tests/actual_tests/weather_status_test.py
First idea: added 1s delay before actions
> Files-versions API: PGSQL + Master branch failing tests

- tests/actual_tests/files_test.py
> second try to fix files versions tests in master

- .github/workflows/analysis-coverage.yml
- Makefile
- README.md
- tests/actual_tests/talk_test.py
- tests/actual_tests/user_status_test.py
Nextcloud 26 is not supported already.
Support Nextcloud 27.1 is EOL in two months.
_This is not mean that `nc-py-api` will stop working with them, there will be just no tests for them._
> removed Nextcloud 26/27

- CHANGELOG.md
- nc_py_api/_version.py
- nc_py_api/ex_app/misc.py
Reference: https://github.com/cloud-py-api/app_api/pull/339
> COMPUTE_DEVICE in lowercase, forced conversion to UpperCase added

- tests/actual_tests/z_special_test.py
- tests/data/nc_pass_confirm_nc31.patch
This is only half of fix for CI, "test_conversation_avatar" test should fail still and need fix too
> CI: "password_confirmation" test fix

- .github/workflows/analysis-coverage.yml
- README.md
In theory, with such a CI simplification, I might have time to add new functionality.
> updated CI to test on newer NC versions
