nc_py_api/_session.py, nc_py_api/users_statuses.py, tests/users_statuses_test.py
Fixed situation when url(not parameter) contained spaces in OCS calls + test that covers this.
=> fixed AppAuth bug, when url contained spaces(OCS calls)

.github/workflows/analysis-coverage.yml, Makefile
adjust CI for last AppEcosystem update
=> daemon-register

.github/workflows/analysis-coverage.yml
We replaced `expose-to-localhost` and `expose-to-global` with one parameter `expose` and values for it: null/"local"/"global" to make it more consistent
=> AppEcosystem new polished `expose` param

.github/workflows/analysis-coverage.yml, CHANGELOG.md, tests/_install.py, tests/weather_status_test.py
app_ecosystem_v2:app:register now accepts input in a json
=> new AppEcosystem fix

.github/workflows/analysis-coverage.yml
Adjustments for finished deploy algorithm
=> adjusted for new AppEcosystem

CHANGELOG.md, docs/index.rst, docs/reference/Files.rst, docs/reference/Session.rst, docs/reference/index.rst, nc_py_api/_session.py, nc_py_api/_version.py, nc_py_api/files.py, tests/files_test.py
=> download2stream implementation

.github/.codecov.yml, .github/workflows/analysis-coverage.yml, MANIFEST.in, Makefile, README.md, nc_py_api/_session.py, scripts/dev_register.sh, tests/gfixture.py
First part of "How to start contributing to nc_py_api"
=> makefile update

.gitignore, .pre-commit-config.yaml, CHANGELOG.md, nc_py_api/__init__.py, nc_py_api/_session.py, nc_py_api/appconfig_preferences_ex.py, nc_py_api/constants.py, nc_py_api/exceptions.py, nc_py_api/preferences.py, nc_py_api/ui_files_actions_menu.py, nc_py_api/users_status.py, nc_py_api/weather_status.py, pyproject.toml, setup.cfg, tests/_install.py, tests/appconfig_preferences_ex_test.py, tests/apps_test.py, tests/files_test.py, tests/gfixture.py, tests/logs_test.py, tests/misc_test.py, tests/nc_app_test.py, tests/preferences_test.py, tests/theming_test.py, tests/ui_file_actions_test.py, tests/users_groups_test.py, tests/users_status_test.py, tests/users_test.py, tests/weather_status_test.py
Adjustments to the last AppEcosystem update
=> preparing next version

.github/.codecov.yml, .github/workflows/analysis-coverage.yml, nc_py_api/_deffered_error.py, nc_py_api/_session.py, pyproject.toml, tests/gfixture.py, tests/misc_test.py, tests/ui_file_actions_test.py
Preparing standalone usage, only as Nextcloud client
=> standalone(as nc client) usage

nc_py_api/appconfig_preferences_ex.py, tests/appconfig_preferences_ex_test.py
Relates to cloud-py-api/app_ecosystem_v2/issues/21
=> added `sensitive` flag for AppCfg

CHANGELOG.md, docs/Options.rst, nc_py_api/_session.py, nc_py_api/options.py, pyproject.toml, tests/misc_test.py
Allows to specify `options` throw environment variables or `.env` file.
Also `options` now are independent in each `Nextcloud` or `NextcloudApp` class, and this allows to specify them with `kwargs`
=> `options` rework

CHANGELOG.md, nc_py_api/users.py, tests/users_test.py
```python3
nc.users.create(TEST_USER_NAME, password=TEST_USER_PASSWORD, groups=["admin"])
```
now works.
=> fix+test for users.create(groups=xxx)

CHANGELOG.md, docs/FirstSteps.rst, examples/as_client/files/find.py, nc_py_api/files/files.py, tests/files_test.py
Fixes #87.
@CooperGerman if you wish, we could add your name to the Authors.md, just need to know it )
P.S: mention me anywhere or create a PR with updated Authors if you want ;)
=> nc.files.find() with "name" param bug fix

examples/as_app/to_gif/appinfo/info.xml, nc_py_api/ex_app/ui/files.py, tests/ui_files_test.py
cloud-py-api/app_ecosystem_v2/pull/45
=> update for `UiActionFileInfo`

CHANGELOG.md, nc_py_api/ex_app/ui/files.py, tests/ui_files_test.py
Now created `FsNode` has the same `file_id` as from WebDAV request with type `str`.
Was not able to do it earlier, as only recent AppEcosystem version start providing Nextcloud Instance ID.
=> made `UiActionFileInfo.to_fs_node` more consistent

CHANGELOG.md, README.md, nc_py_api/_version.py, nc_py_api/files/__init__.py, nc_py_api/files/files.py, tests/files_test.py
- TrashBin API:
* `trashbin_list`
* `trashbin_restore`
* `trashbin_delete`
* `trashbin_cleanup`
=> added TrashBin API

.run/ToGif (27).run.xml, .run/ToGif(28).run.xml, examples/as_app/skeleton/Makefile, examples/as_app/talk_bot/Makefile, examples/as_app/to_gif/Makefile
Makefiles had a typo for stable27
Currently on master branch on Nextcloud Server repo, `filesplugin.js` is broken, so added dev run config for ToGif for stable27
=> fixed typo + add dev conf for ToGif on stable27

.github/workflows/analysis-coverage.yml, CHANGELOG.md, docs/reference/ActivityApp.rst, docs/reference/Exceptions.rst, docs/reference/index.rst, nc_py_api/_exceptions.py, nc_py_api/_misc.py, nc_py_api/_session.py, nc_py_api/_version.py, nc_py_api/activity.py, nc_py_api/files/sharing.py, nc_py_api/nextcloud.py, nc_py_api/notifications.py, scripts/ci_register.sh, scripts/dev_register.sh, tests/actual_tests/activity_test.py, tests/actual_tests/files_sharing_test.py, tests/actual_tests/misc_test.py, tests/actual_tests/notifications_test.py
Also added `nc_iso_time_to_datetime` internal method to parse time for shares, notifications and activities.
This leads to fix of a bug when `NotificationInfo.time` was always incorrectly parsed and equal to `datetime(1970,1,1)`
=> added Activities API

CHANGELOG.md, README.md, docs/reference/Files/Files.rst, nc_py_api/_session.py, nc_py_api/files/__init__.py, nc_py_api/files/files.py, tests/actual_tests/conftest.py, tests/actual_tests/files_test.py
Note: New `list_by_criteria` should be much faster then `listfav`
=> FilesAPI: SystemTags implementation

.github/workflows/analysis-coverage.yml, docs/NextcloudTalkBotTransformers.rst, docs/index.rst, docs/reference/ExApp.rst
=> Talk Bot App with Python Transformers [docs]

benchmarks/aa_overhead_common.py, examples/as_app/talk_bot/src/main.py, examples/as_app/talk_bot_multi/src/main.py, nc_py_api/_misc.py, nc_py_api/files/__init__.py, nc_py_api/files/files.py, nc_py_api/talk_bot.py, nc_py_api/weather_status.py, pyproject.toml, tests/actual_tests/files_test.py, tests/actual_tests/talk_test.py
=> added `S`, `RET`, `RUF` ruff checks

CHANGELOG.md, nc_py_api/_session.py, nc_py_api/files/files.py, nc_py_api/options.py, tests/actual_tests/files_test.py, tests/actual_tests/options_test.py
There are two versions of the chunking API. Version 1 is the original version and version 2 was built as a backward compatible extension to support uploads directly to supporting target storages like S3. Version 2 is the recommended version to use.
---
https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/chunking.html
=> implemented chunked file upload v2

CHANGELOG.md, docs/reference/Talk.rst, nc_py_api/_talk_api.py, nc_py_api/_version.py, nc_py_api/talk.py, tests/actual_tests/talk_test.py
Poll API is relatively small and easy :)
=> Nextcloud Talk: Polls API

CHANGELOG.md, docs/reference/ExApp.rst, docs/reference/Nextcloud.rst, docs/reference/index.rst, examples/as_app/skeleton/appinfo/info.xml, examples/as_app/skeleton/requirements.txt, examples/as_app/talk_bot/appinfo/info.xml, examples/as_app/talk_bot/requirements.txt, examples/as_app/talk_bot_ai/appinfo/info.xml, examples/as_app/talk_bot_ai/requirements.txt, examples/as_app/talk_bot_multi/appinfo/info.xml, examples/as_app/talk_bot_multi/requirements.txt, examples/as_app/to_gif/appinfo/info.xml, examples/as_app/to_gif/requirements.txt, nc_py_api/_version.py, nc_py_api/ex_app/__init__.py, nc_py_api/ex_app/misc.py, tests/actual_tests/misc_test.py
- NextcloudApp: The `ex_app.verify_version` function to simply check whether the application has been updated.
- NextcloudApp: Updated `info.xml` in examples to reflect upcoming changes in the [AppStore](https://github.com/nextcloud/appstore/pull/1145)
---
Hopefully, starting from this version there will be availability to upload applications into the AppStore(will be in beta stage)
=> Preparing AppStore support

CHANGELOG.md, docs/reference/ExApp.rst, docs/reference/Talk.rst, nc_py_api/_talk_api.py, nc_py_api/ex_app/ui/files.py, nc_py_api/files/__init__.py, nc_py_api/files/sharing.py, nc_py_api/talk.py, tests/actual_tests/talk_test.py
Added simple APIs that will make life much easier for chats: sending a file/directory and converting a text message containing the file/directory directly into FsNode
Later will write and examples and add them to documentation, but these API are really simple.
=> TalkAPI: added send_file; receive_messages can return TalkFileMessage

.github/workflows/analysis-coverage.yml, CHANGELOG.md, README.md, docs/Installation.rst, docs/reference/Calendar.rst, docs/reference/index.rst, nc_py_api/_session.py, nc_py_api/_version.py, nc_py_api/calendar.py, nc_py_api/nextcloud.py, pyproject.toml, tests/actual_tests/calendar_test.py
Fixes #120
In future we should use our own DAV stuff that was written for Files already and Objects API from `caldav`, so we need to implement our custom `DAVClient` and `DAVResponse` with compatible format for `caldav`.
=> added CalendarAPI with the help of caldav

.github/workflows/analysis-coverage.yml, CHANGELOG.md, README.md, benchmarks/aa_overhead_dav_download.py, benchmarks/aa_overhead_dav_download_stream.py, benchmarks/aa_overhead_dav_upload.py, benchmarks/aa_overhead_dav_upload_stream.py, docs/reference/Notes.rst, docs/reference/index.rst, nc_py_api/_session.py, nc_py_api/ex_app/defs.py, nc_py_api/nextcloud.py, nc_py_api/notes.py, scripts/ci_register.sh, scripts/dev_register.sh, tests/actual_tests/calendar_test.py, tests/actual_tests/misc_test.py, tests/actual_tests/notes_test.py
tests will come with next commit...
=> initial commit for Notes API

CHANGELOG.md, docs/reference/Talk.rst, nc_py_api/_talk_api.py, nc_py_api/talk.py, nc_py_api/user_status.py, tests/actual_tests/talk_test.py
While writing examples for documentation on how to work with the Talk API, I realized that there was no method for obtaining a list of participants in a conversation.
**Now it is :)**
A bug was also found that the statuses for one-to-one conversations were always empty.
**Corrected and added a test for this.**
=> TalkAPI: added `list_participants` method + fix for statuses

CHANGELOG.md, docs/reference/Users/Users.rst, nc_py_api/_version.py, nc_py_api/users.py, tests/actual_tests/conftest.py, tests/actual_tests/misc_test.py, tests/actual_tests/users_test.py, tests/conftest.py
* `users.get_details` renamed to `get_user` and returns a class instead of a dictionary.
* Optional argument `displayname` in `users.create` renamed to `display_name`.
* `users.get_details` with empty parameter in some cases was raised exception.
=> reworked `users.get_details`

CHANGELOG.md, nc_py_api/apps.py, tests/actual_tests/apps_test.py
Made `ExAppInfo` class to be the in same format as all others.
=> Adjusted `apps.ExAppInfo` dataclass.

CHANGELOG.md, docs/reference/Users/Notifications.rst, nc_py_api/activity.py, nc_py_api/apps.py, nc_py_api/files/__init__.py, nc_py_api/notes.py, nc_py_api/notifications.py, nc_py_api/talk.py, nc_py_api/talk_bot.py, nc_py_api/user_status.py, nc_py_api/users.py, nc_py_api/users_groups.py, tests/_talk_bot.py, tests/actual_tests/activity_test.py, tests/actual_tests/apps_test.py, tests/actual_tests/files_test.py, tests/actual_tests/notes_test.py, tests/actual_tests/notifications_test.py, tests/actual_tests/talk_test.py, tests/actual_tests/user_status_test.py, tests/actual_tests/users_groups_test.py, tests/actual_tests/users_test.py
* `__repr__` method added for most objects(previously it was only present for `FsNode`).
* `notifications.Notification` class has been rewritten in the same format as all the others.
=> `__repr__` method

CHANGELOG.md, nc_py_api/_session.py, nc_py_api/nextcloud.py, tests/actual_tests/user_status_test.py
By default, the login passed to the Nextcloud class was taken as the user name.
If a backend other than the Database is used, these two values do not match each other, that is, the login can be:
"milena.kvitkova@domain.com", and the user ID for making API requests will be: "milena"
Note: This bug does not apply to the NextcloudApp class, because there the AppAPI transmits the user ID, and not the user login - this only affects use as a client.
=> Client mode: LDAP user_id bug fix

CHANGELOG.md, nc_py_api/users.py, tests/actual_tests/users_test.py
After this we can write docs and guides 🥳
=> added `get_avatar` method

.run/TalkBotAI (27).run.xml, .run/TalkBotAI (28).run.xml, .run/ToGif (28).run.xml, CHANGELOG.md, examples/as_app/skeleton/Makefile, examples/as_app/skeleton/requirements.txt, examples/as_app/talk_bot/Makefile, examples/as_app/talk_bot/requirements.txt, examples/as_app/talk_bot_ai/Makefile, examples/as_app/talk_bot_ai/requirements.txt, examples/as_app/talk_bot_ai/src/main.py, examples/as_app/talk_bot_multi/Makefile, examples/as_app/talk_bot_multi/requirements.txt, examples/as_app/to_gif/Makefile, examples/as_app/to_gif/requirements.txt, nc_py_api/_version.py, nc_py_api/ex_app/integration_fastapi.py, nc_py_api/nextcloud.py, pyproject.toml, scripts/ci_register.sh, scripts/dev_register.sh, tests/_install_init_handler_models.py, tests/_tests_at_the_end.py
Checks will fail, it is expected until new version of AppAPI will not be released.
=> AppAPI 1.1.0, `/init` endpoint

.github/workflows/analysis-coverage.yml, nc_py_api/ex_app/integration_fastapi.py, tests/_install.py, tests/_install_init_handler_models.py, tests/_tests_at_the_end.py
PHP_CLI_SERVER_WORKERS=2 to `php -S`
This should prevent timeouts during the installation flow.
=> An attempt to fix the installation flow

CHANGELOG.md, nc_py_api/_session.py
Probably this will fix tests from #157
=> sign AppAPI requests with `update` method to support `httpx.Headers`

nc_py_api/files/files.py
File operations need to have utf-8 headers otherwise special allowed characters will break the file action as they will encoded to ascii per default.
Fixes # 
If you have files with äöü etc. you will get an ascii encoding error cause of the reference in the Header. 
This fixes this issue 
* Set Headers to encode to UTF-8 on file operations
=> Explicit set utf-8 headers for file operations

AUTHORS, CHANGELOG.md, nc_py_api/files/files.py, tests/actual_tests/files_test.py
The same bug that was found in: #157
=> tests + correct utf-8 header set for `upload_stream`

.github/workflows/analysis-coverage.yml
=> added stable28 branch of Nextcloud

.github/workflows/analysis-coverage.yml, CHANGELOG.md, nc_py_api/ex_app/integration_fastapi.py, tests/_install_async.py
Next code should be allowed for some folks, that love `async` :
```python3
@asynccontextmanager
async def lifespan(_app: FastAPI):
ex_app.set_handlers(APP, enabled_handler, heartbeat_callback, init_handler=init_handler)
yield
async def enabled_handler(enabled: bool, nc: NextcloudApp) -> str:
print(f"enabled_handler: enabled={enabled}", flush=True)
if enabled:
nc.log(ex_app.LogLvl.WARNING, f"Hello from {nc.app_cfg.app_name} :)")
else:
nc.log(ex_app.LogLvl.WARNING, f"Bye bye from {nc.app_cfg.app_name} :(")
return ""
async def init_handler(nc: NextcloudApp):
nc.set_init_status(100)
async def heartbeat_callback():
return "ok"
```
`set_handlers` should support all `Callable` to be awaitable.
=> added "async" support for `set_handlers`

nc_py_api/_exceptions.py, nc_py_api/_preferences.py, nc_py_api/_preferences_ex.py, nc_py_api/_session.py, nc_py_api/_talk_api.py, nc_py_api/activity.py, nc_py_api/apps.py, nc_py_api/calendar.py, nc_py_api/ex_app/ui/files_actions.py, nc_py_api/ex_app/ui/resources.py, nc_py_api/ex_app/ui/top_menu.py, nc_py_api/files/files.py, nc_py_api/files/sharing.py, nc_py_api/nextcloud.py, nc_py_api/notes.py, nc_py_api/notifications.py, nc_py_api/user_status.py, nc_py_api/users.py, nc_py_api/users_groups.py, nc_py_api/weather_status.py, tests/actual_tests/appcfg_prefs_ex_test.py, tests/actual_tests/logs_test.py, tests/actual_tests/misc_test.py, tests/actual_tests/talk_test.py, tests/actual_tests/users_test.py
_Because initially the project was written for a different AppAPI authentication, where all transmitted data was signed - there was a lot of unnecessary code left._
This pull request will cover it all, total refactoring and simplification of the code.
**After this, it will be possible to make public methods for communicating with Nextcloud, which would make it easier to connect third-party packages.**
**It is also necessary to clean up the code before adding asynchronous methods.**
* set `AUTHORIZATION-APP-API` header with help of `event_hook`
* set default `timeout` during `httpx.adapter` creation
* set `base_url` during `httpx.adapter` creation
* download_directory_as_zip: directly call `session.adapter.stream` (removed `_session.get_stream`)
* all …
=> Clean-up/Refactoring of old code

CHANGELOG.md, docs/NextcloudTalkBotTransformers.rst, examples/as_app/talk_bot_ai/lib/main.py, nc_py_api/ex_app/integration_fastapi.py, tests/_install_init_handler_models.py, tests/actual_tests/nc_app_test.py
* set_handlers: `models_to_fetch` and `models_download_params` united in one more flexible parameter.
=> set_handlers:  changed type of `models_to_fetch`, removed "models_download_params"

CHANGELOG.md, nc_py_api/_version.py, nc_py_api/nextcloud.py, tests/actual_tests/misc_test.py
Many OCS have not yet been described, but can now be used quite easily using the "osc" method.
_I couldn't add it before because... I didn’t know whether the OCS prototype would change or not, now I already know that it won’t._
=> added public `ocs` method

CHANGELOG.md, nc_py_api/_version.py, nc_py_api/files/files.py, tests/actual_tests/files_test.py
Fixes #191 .
Looks like this error was introduced in `0.7.0` version, where I refactored all code.
_Fixed and adjusted tests suite to detect this_
Tomorrow will check what else DAV methods affected by this error and fix that in separate PR.
=> files: added url quote to mkdir and delete

CHANGELOG.md, nc_py_api/files/files.py, tests/actual_tests/conftest.py, tests/actual_tests/files_test.py
Ref #193
The same as in #192 but for all other DAV methods.
Tests were expanded to catch this case.
=> added quote to urls, adjusted tests to cover this

nc_py_api/nextcloud.py, tests/actual_tests/misc_test.py
Ref: [#193](https://github.com/cloud-py-api/nc_py_api/issues/193#issuecomment-1870923612) point 1.
Added a separate login function named "perform_login" that can be called manually for easy check whether the login success or not
=> added "perform_login" method

CHANGELOG.md, nc_py_api/_session.py, nc_py_api/ex_app/defs.py, scripts/ci_register.sh, scripts/dev_register.sh, tests/actual_tests/misc_test.py, tests/actual_tests/nc_app_test.py
This code were not working:
```python3
nc.ocs("GET", "/ocs/v2.php/core/whatsnew")
```
this PR fixes it, for OCS that return `Http::STATUS_NO_CONTENT` we return empty list.
In addition added `ALL` API scope, ref: cloud-py-api/app_api/pull/190
Previous commit: https://github.com/cloud-py-api/nc_py_api/commit/8fd175adeb038f1f5f16dde076cc8a2ee2eb052c was added fast to just implement `ALL` API scope tests in AppAPI repo.
=> skip OCS parsing when status == NO CONTENT

CHANGELOG.md, docs/reference/ExApp.rst, nc_py_api/ex_app/providers/providers.py, nc_py_api/ex_app/providers/text_processing.py, tests/actual_tests/text_processing_provider_test.py
Ref1: cloud-py-api/app_api/pull/191
Ref2: [Implementing a TextProcessing provider](https://docs.nextcloud.com/server/28/developer_manual/digging_deeper/text_processing.html#implementing-a-textprocessing-provider)
_Examples will be later, thinking about concept, want them to be production ready._
=> added TextProcessing Provider API

nc_py_api/ex_app/providers/text_processing.py, tests/actual_tests/text_processing_provider_test.py
Ref: https://github.com/cloud-py-api/app_api/pull/208
We decided to make Provider API in a way to easy implement in ASGI applications.
=> added `report_result` method to TextProcessing providers API

CHANGELOG.md, docs/NextcloudApp.rst, docs/conf.py, nc_py_api/_session.py, nc_py_api/_version.py, nc_py_api/ex_app/__init__.py, nc_py_api/ex_app/integration_fastapi.py, nc_py_api/nextcloud.py, tests/_install_async.py
For some applications it will be useful to simply set global authentication to all endpoints and not write in each endpoint:
New:
```python3
APP = FastAPI(lifespan=lifespan)
APP.add_middleware(ex_app.AppAPIAuthMiddleware)
```
Old:
```python3
@APP.post("/verify_initial_value")
async def verify_initial_value(
_nc: typing.Annotated[NextcloudApp, Depends(nc_app)],   # <---- this is no needed when using new Global Middleware
input1: Button1Format,
):
print("Old value: ", input1.initial_value)
return responses.JSONResponse(content={"initial_value": str(random.randint(0, 100))}, status_code=200)
```
Limitations: 
`Talk bots` endpoints using another Auth type, and they should be added to `disable_for` parameter of `AppAPIAuthMiddleware`.
=> added optional global AppAPIAuth middleware

CHANGELOG.md, nc_py_api/files/__init__.py, tests/actual_tests/files_sharing_test.py
* class `Share`: added missing `file_source_id`, `can_edit`, `can_delete` properties.
* class `Share`.raw_data marked as deprecated and changed to `_raw_data`.
=> share API adjustments

tests/_talk_bot.py, tests/_talk_bot_async.py
Nothing special, just clean up.
Need to clear this from the result of Tests on GitHub:
```
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
result = await app(  # type: ignore[func-returns-value]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
return await self.app(scope, receive, send)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/uvicorn/middleware/message_logger.py", line 84, in __call__
raise exc from None
File …
```
=> CI-tests: specify default value for dict.pop operation

docs/NextcloudApp.rst, docs/NextcloudTalkBot.rst, docs/conf.py, examples/as_app/skeleton/Makefile, examples/as_app/skeleton/appinfo/info.xml, examples/as_app/talk_bot/Makefile, examples/as_app/talk_bot/appinfo/info.xml, examples/as_app/talk_bot_ai/Makefile, examples/as_app/talk_bot_ai/appinfo/info.xml, examples/as_app/to_gif/Makefile, examples/as_app/to_gif/appinfo/info.xml, examples/as_app/ui_example/Makefile, examples/as_app/ui_example/appinfo/info.xml, nc_py_api/_version.py, nc_py_api/ex_app/defs.py, nc_py_api/nextcloud.py, scripts/ci_register.sh, scripts/dev_register.sh, tests/actual_tests/nc_app_test.py
Ref: https://github.com/cloud-py-api/app_api/pull/220
No more "optional API Scopes", lets make all simpler :)
=> appapi-2.0.3-api-scopes

.github/.codecov.yml, .github/workflows/analysis-coverage.yml, nc_py_api/apps.py
Moves all coverage upload to a separate step, that can be easy rerun from GitHub UI.
Ref: https://github.com/codecov/codecov-action/issues/926
=> CI: coverage upload fix

CHANGELOG.md, README.md, docs/NextcloudUiApp.rst, docs/reference/ExApp.rst, examples/as_app/ui_example/lib/main.py, nc_py_api/_preferences_ex.py, nc_py_api/ex_app/__init__.py, nc_py_api/ex_app/ui/settings.py, nc_py_api/ex_app/ui/ui.py, tests/actual_tests/ui_settings_test.py
As API of Declarative Settings is very simple the `nc.ui.settings.register_form` method can accept `SettingsForm` data class or a raw dict that will be passed to AppAPI.
Ref: https://github.com/cloud-py-api/app_api/pull/149
=> Declarative Settings UI API (Nextcloud 29)

CHANGELOG.md, docs/NextcloudApp.rst, docs/NextcloudTalkBot.rst, examples/as_app/skeleton/lib/main.py, examples/as_app/talk_bot/lib/main.py, examples/as_app/talk_bot/requirements.txt, examples/as_app/talk_bot_ai/lib/main.py, examples/as_app/talk_bot_ai/requirements.txt, examples/as_app/to_gif/lib/main.py, examples/as_app/to_gif/requirements.txt, examples/as_app/ui_example/lib/main.py, examples/as_app/ui_example/requirements.txt, nc_py_api/ex_app/integration_fastapi.py, nc_py_api/nextcloud.py, pyproject.toml, tests/_install.py, tests/_install_async.py, tests/_talk_bot.py, tests/_talk_bot_async.py, tests/actual_tests/nc_app_test.py
Old `set_handlers`
```python3
def set_handlers(
fast_api_app: FastAPI,
enabled_handler: typing.Callable[[bool, AsyncNextcloudApp | NextcloudApp], typing.Awaitable[str] | str],
heartbeat_handler: typing.Callable[[], typing.Awaitable[str] | str] | None = None,
init_handler: typing.Callable[[AsyncNextcloudApp | NextcloudApp], typing.Awaitable[None] | None] | None = None,
models_to_fetch: dict[str, dict] | None = None,
map_app_static: bool = True,
):
```
New `set_handlers`:
```python3
def set_handlers(
fast_api_app: FastAPI,
enabled_handler: typing.Callable[[bool, AsyncNextcloudApp | NextcloudApp], typing.Awaitable[str] | str],
default_heartbeat: bool = True,
default_init: bool = True,
models_to_fetch: dict[str, dict] | None = None,
map_app_static: bool = True,
):
```
Main change is now if …
=> `set_handlers`: heartbeat_handler/init_handler params rework

.github/workflows/analysis-coverage.yml, CHANGELOG.md, docs/reference/Files/Files.rst, nc_py_api/__init__.py, nc_py_api/_version.py, nc_py_api/files/__init__.py, nc_py_api/files/_files.py, nc_py_api/files/files.py, tests/actual_tests/files_test.py
Implemented using WebDAV requests.
```python3
async def lock(self, path: FsNode | str, lock_type: LockType = LockType.MANUAL_LOCK) -> None:
"""Locks the file.
.. note:: Exception codes: 423 - existing lock present.
"""
pass
async def unlock(self, path: FsNode | str) -> None:
"""Unlocks the file.
.. note:: Exception codes: 412 - the file is not locked, 423 - the lock is owned by another user.
""" 
pass   
```    
Reference: https://github.com/nextcloud/files_lock
=> added Files Locking support

CHANGELOG.md, nc_py_api/ex_app/providers/translations.py, tests/actual_tests/translation_provider_test.py
Refs: 
https://github.com/cloud-py-api/app_api/pull/232
https://docs.nextcloud.com/server/28/developer_manual/digging_deeper/translation.html#providing-language-detection
=> TranslationProvider: added `detect_lang_callback_url` param

.github/SECURITY.md, CHANGELOG.md, docs/conf.py, docs/reference/ExApp.rst, examples/as_app/skeleton/Makefile, examples/as_app/skeleton/requirements.txt, examples/as_app/talk_bot/HOW_TO_INSTALL.md, examples/as_app/talk_bot/Makefile, examples/as_app/talk_bot_ai/Makefile, examples/as_app/to_gif/Makefile, nc_py_api/_session.py, nc_py_api/_version.py, nc_py_api/ex_app/__init__.py, nc_py_api/ex_app/defs.py, nc_py_api/ex_app/integration_fastapi.py, nc_py_api/ex_app/misc.py, nc_py_api/files/files.py, scripts/dev_register.sh, tests/_app_security_checks.py, tests/actual_tests/files_test.py
Maintenance update:
* applied changes from AppAPI 2.3.0 (renamed vars)
* fixed CI for Nextcloud Master with PGSQL(some server bug?)
* removed non needed stuff(optional API scopes)
* updated Security.md
=> NextcloudApp: polishing API, AppAPI `2.3.0`

CHANGELOG.md, nc_py_api/users.py
=> user creation: fixed  incorrect "displayname" param

CHANGELOG.md, docs/reference/ExApp.rst, nc_py_api/ex_app/events_listener.py, nc_py_api/nextcloud.py, tests/actual_tests/events_listener_test.py
API to register Events Listeners for NextcloudApp
Reference: https://github.com/cloud-py-api/app_api/pull/259
=> feat: Events Listeners registration API

CHANGELOG.md, docs/NextcloudApp.rst, docs/reference/Files/Files.rst, examples/as_app/to_gif/lib/main.py, nc_py_api/_session.py, nc_py_api/_version.py, nc_py_api/ex_app/__init__.py, nc_py_api/ex_app/ui/files_actions.py, nc_py_api/files/__init__.py, tests/actual_tests/ui_files_actions_test.py
Now in ExApp you can conveniently accept many files at once, and this is very cool  🥳
Reference: https://github.com/cloud-py-api/app_api/pull/284
=> AppAPI 2.6.0 - new FileActionsV2

.github/workflows/analysis-coverage.yml, Makefile, tests/actual_tests/files_test.py
Restored the old tests for the file versions, because that commit with optimization of working with file versions in the Nextcloud server repository was backported on the NC 27, 28 versions of the server - I simply disabled this test on the PGSQL database, where these tests fails.
=> restore old file_version tests, skip them on PGSQL

CHANGELOG.md, nc_py_api/__init__.py, nc_py_api/files/_files.py, nc_py_api/files/files_async.py, nc_py_api/nextcloud.py, tests/actual_tests/files_test.py
Fixes #259
```python3
nc = nc_py_api.Nextcloud(nc_auth_user="admin", nc_auth_pass="admin", nextcloud_url="http://stable29.local")
some_file = nc.files.by_path("New folderz/1.txt")
some_file_tags = nc.files.get_tags(some_file)
print(some_file_tags)
```
Output:
`[<SystemTag id=1, name=first>, <SystemTag id=2, name=second>]`
=> added `files.get_tags` function

.github/workflows/analysis-coverage.yml, tests/data/nc_pass_confirm.patch
The patch just stopped working because there was a commit to the master and backports to other versions of the cloud.
Reference: https://github.com/nextcloud/server/commit/02313013ad9094ea0ec52f30672971ab03f4ec15
=> updated "patch" for testing NC reflecting last changes

CHANGELOG.md, nc_py_api/nextcloud.py
Reference: https://github.com/cloud-py-api/app_api/pull/318
_Required functionality when wrapping external service as ExApp_
=> added `enabled_state` property for NextcloudApp

CHANGELOG.md, docs/reference/ExApp.rst, nc_py_api/_session.py, nc_py_api/ex_app/providers/providers.py, nc_py_api/ex_app/providers/task_processing.py
Not working entirely yet, getting the next task fails with authentication problems.
=> feat: Add task processing API

docs/NextcloudApp.rst, docs/NextcloudSysApp.rst, docs/index.rst, examples/as_app/talk_bot/Makefile, examples/as_app/talk_bot/appinfo/info.xml, examples/as_app/talk_bot/requirements.txt, examples/as_app/talk_bot_ai/Makefile, examples/as_app/talk_bot_ai/appinfo/info.xml, examples/as_app/talk_bot_ai/requirements.txt, examples/as_app/to_gif/Makefile, examples/as_app/to_gif/appinfo/info.xml, examples/as_app/to_gif/requirements.txt, nc_py_api/_session.py, nc_py_api/_version.py, nc_py_api/apps.py, nc_py_api/nextcloud.py, scripts/ci_register.sh, scripts/dev_register.sh, tests/actual_tests/apps_test.py
We are making ExApps more like usual PHP Apps for Nextcloud.
Now any ExApp is allowed to impersonate any user, no need "system" flag for this.
Reference: https://github.com/cloud-py-api/app_api/pull/323
=> dropped "system" flag for ExApps

.github/workflows/analysis-coverage.yml, nc_py_api/ex_app/providers/task_processing.py
Counter part for https://github.com/cloud-py-api/app_api/pull/324
=> feat(TaskProcessing): Allow defining custom task types

nc_py_api/ex_app/integration_fastapi.py
Models downloaded wrt `models_to_fetch` dict have the output path of the downloaded model files in the "path" key for each model.
=> feat: store model download paths in "path" key

CHANGELOG.md, docs/reference/Webhooks.rst, docs/reference/index.rst, nc_py_api/nextcloud.py, nc_py_api/webhooks.py, pyproject.toml, tests/actual_tests/files_sharing_test.py, tests/gfixture_set_env.py
Not finished yet, because... I'm waiting for this to be finalized on the server.
The technology is very powerful, probably better than what happened with ExApp.
It can also be used as a Nextcloud client, but the client must have administrator access.
Some docs(and maybe article?) will come before NC30 release.
Reference: https://github.com/nextcloud/server/pull/46477
=> NC30: `webhook_listeners` app support

CHANGELOG.md, nc_py_api/_version.py, nc_py_api/files/files.py
=> fixed `nc.files.makedirs` on Windows

CHANGELOG.md, docs/reference/ExApp.rst, nc_py_api/ex_app/providers/task_processing.py, pyproject.toml
All related PRs:
https://github.com/cloud-py-api/nc_py_api/pull/284
https://github.com/cloud-py-api/app_api/pull/359
https://github.com/nextcloud/translate2/pull/11
=> feat: Add enum and default value support in task processing

docs/DevSetup.rst
=> added missing step to the DevSetup

nc_py_api/talk_bot.py
Sample chat message structure: https://nextcloud-talk.readthedocs.io/en/latest/bots/#sample-chat-message
=> feat: add message_type property to TalkBotMessage

CHANGELOG.md, nc_py_api/_version.py, nc_py_api/nextcloud.py, tests/actual_tests/logs_test.py
* Suppress all exceptions during `nc.log`
It's strange that I didn't do this before, without it we won't be able to use logging during exception handling.
=> Suppress exceptions in `nc.log`

CHANGELOG.md, nc_py_api/ex_app/__init__.py, nc_py_api/ex_app/logging.py, nc_py_api/nextcloud.py, tests/actual_tests/logs_test.py
Usage:
```python3
import logging
from pathlib import Path
from os import environ
import nc_py_api
environ["APP_ID"] = "nc_py_api"
environ["APP_VERSION"] = "1.0.0"
environ["APP_SECRET"] = "12345"
environ["NEXTCLOUD_URL"] = "http://nextcloud.local"
if __name__ == "__main__":
nc_app = nc_py_api.NextcloudApp()
logging.basicConfig(
level=logging.INFO,
format="%(asctime)s: [%(funcName)s]:%(levelname)s: %(message)s",
datefmt="%H:%M:%S",
)
logging.getLogger("httpx").setLevel(logging.ERROR)  # not needed, but better to hide spam to console
nc_py_api.ex_app.setup_nextcloud_logging() # setup logging handler in one line of code
logging.fatal("Fatal test")
logging.error("Error test")
logging.warning("Warning test")
logging.info("Info test")
logging.debug("Debug test")
logging.fatal("Fatal test2")
try: …
```
=> NextcloudApp: `setup_nextcloud_logging` function for transparent logging

nc_py_api/files/__init__.py
Fixes #296  .
* Regex instantiated on import for performance
* Regex to fetch accurate user path regardless of subpath
* Regex to fetch accurate user regardless of subpath
Tested against three Nextcloud instances, with or without /nextcloud and index.php in the path.
=> Fix user and user_path in FSNode for subpath deployments

.github/workflows/analysis-coverage.yml
Since Nextcloud 30.0.1 version, AppAPI has become built into the server, so now the `stable29` branch is the branch for Nextcloud `28` and `29`, and the `main` branch corresponds to the `master` branch of the server, and branch 30 is there for Nextcloud `30.0.1+`
It is tough..
=> CI fix: app_api is now bundled app from NC 30.0.1

nc_py_api/_session.py, nc_py_api/files/files.py, nc_py_api/files/files_async.py
In 31 Nextcloud, the old method of downloading folders has simply been removed.
The changes are very useful, downloading a folder through webdav has become more pleasant, and now we can download it in `tar` format, something like this:
```python
nc.files.download_directory_as_zip("test_empty_dir_in_dir", "2.tar", format="x-tar")
```
Default usage doesn't changed, so **no something breaking** for nc_py_api usage.
References: 
* https://github.com/nextcloud/documentation/pull/12247
* https://github.com/nextcloud/server/pull/48098
=> Fix of download_directory_as_zip function for NC31

.github/workflows/analysis-coverage.yml, AUTHORS, CHANGELOG.md, nc_py_api/_version.py, nc_py_api/webhooks.py
Mainly needed for ExApps, but can also be used in some scripts with admin rights.
=> added "webhooks.unregister_all"

nc_py_api/_version.py, nc_py_api/options.py, pyproject.toml
After internal discussion with @kyteinsky when we tested this https://github.com/nextcloud/app_api/pull/448 - it was found out that the `test-deploy` ExApp from AppAPI "Test Deploy" button action fails in such setups, since the Python library "httpx" ignores system certificates by default.
reference: https://github.com/encode/httpx/issues/302
Temporary workaround, until "httpx" will change it's behavior.
=> Use system trust store by default

nc_py_api/_session.py
Fixes #327
* Added a custom header in the format `ExApp/test-deploy/1.1.0 (httpx/0.24.1)` to help "system administrators" identify which requests are taking a long time to complete.
=> set custom "User-Agent" for ExApps

tests/actual_tests/files_sharing_test.py
something this logic is constantly changing in the NC server repository, let's just simplify the test a little
=> CI: fixed "share create" tests

nc_py_api/_session.py
Reason: AppAPI are already a bundled app, that distributes with Nextcloud Server and always have a version that Nextcloud Server have and this header is not needed anymore.
Starting from **Nextcloud 32** AppAPI will stop sending this header to the ExApps.
We do not drop sending `AA-VERSION` header to the NC, until we drop the support of NC31, as old AppAPI versions still require those header, we just removing this header from the required header list.
=> ExApps should not require `AA-VERSION` header

nc_py_api/files/__init__.py, nc_py_api/files/_files.py
*Added creation date for the fs node info
*Edit default request to also get creation date
=> add creation date to fs node info

nc_py_api/files/__init__.py, tests/actual_tests/files_test.py
=> fix coverage for "creation_date"

nc_py_api/ex_app/integration_fastapi.py
ExApps starting with Nextсloud 32 are planned to have **websockets** support - we enable authentication in advance, so that there is time to rebuild ExApps.
=> enabled AppAPIAuthMiddleware for websockets(Nextcloud 32+)

nc_py_api/_session.py, nc_py_api/nextcloud.py
Sends the response text immediately if the response type is set to `json`
Made for dealing with a JSONResponse that does not include an OCS object
=> fix: Handle JSON responses

.github/workflows/analysis-coverage.yml
Related PR in the Nextcloud Server repo: 
https://github.com/nextcloud/server/pull/50905
=> fix CI: disabled NC ratelimiting

CHANGELOG.md, nc_py_api/_session.py
Fixes #352 .
By switching from `iter_raw` to `iter_bytes`, **httpx will automatically handle the decompression** if the `Content-Encoding: gzip` header is present. If the header is absent or specifies no compression (like identity), `iter_bytes` will yield the original bytes, just like `iter_raw` would have.
=> fix: support for compressed content in download2stream method.

nc_py_api/files/_files.py, tests/actual_tests/files_test.py
Fixes #347 .
This PR fixes incorrect handling of `datetime` and `date` objects in WebDAV `find()` queries. Previously, passing a `datetime` resulted in an invalid string format like `2025-03-10 12:34:56.123456`, causing Nextcloud to misinterpret the value in `<d:literal>`.
**Changes made:**
- Added `_dav_literal()` helper to format datetime values as RFC 3339 strings (`2025-03-10T12:34:56Z`)
- Updated `build_search_req()` to use this helper when generating `<d:literal>` values
This ensures proper comparison logic for operators like `"gt"` and `"lt"` when filtering by `last_modified` or other time-based properties.
Fixes issues where files were incorrectly included or excluded due to string-based comparison.
=> feat: convert datetime values to RFC 3339 in WebDAV search literals

nc_py_api/_preferences_ex.py, nc_py_api/_version.py, nc_py_api/ex_app/ui/settings.py, tests/actual_tests/appcfg_prefs_ex_test.py
Related to: https://github.com/cloud-py-api/nc_py_api/issues/344, https://github.com/nextcloud/server/pull/53121, https://github.com/nextcloud/app_api/pull/585
Add sensitive Declarative settings field type.
=> feat(declarativeSettings): sensitive field type support

nc_py_api/users.py
Introduces a new 'wipe' method to disconnect a user from the Nextcloud server and delete all local data stored on the user's devices via the OCS API.
=> feat(users): add wipe method to UsersAPI

docs/conf.py, examples/as_app/talk_bot/lib/main.py, nc_py_api/_exceptions.py, nc_py_api/_session.py, nc_py_api/calendar_api.py, nc_py_api/ex_app/integration_fastapi.py, nc_py_api/files/_files.py, nc_py_api/files/files.py, nc_py_api/files/files_async.py, nc_py_api/loginflow_v2.py, nc_py_api/nextcloud.py, nc_py_api/notes.py, nc_py_api/options.py, nc_py_api/talk_bot.py, pyproject.toml, tests/_app_security_checks.py, tests/_install_wait.py, tests/actual_tests/logs_test.py, tests/actual_tests/misc_test.py, tests/actual_tests/talk_bot_test.py
Fixes #365 
* Move from httpx to niquests.
Quick history around that, httpx is being a bit stale for a couple of years now and report of spurious errors like the one in #365 is killing the global UX of that library. Not only that but httpx is absolutely unusable in the freethreaded build for example, it crash instantly on any attempt. Moreover the performance are often pointed out, especially in async. While Niquests isn't faster than aiohttp right now, it's better than requests and httpx.
Finally, a touch of hope, we recently were selected into the [GitHub Secure Open Source Program](https://github.blog/open-source/maintainers/securing-the-supply-chain-at-scale-starting-with-71-important-open-source-projects/#developer-utilities-and-cli-helpers-%f0%9 …
=> feat(http): switch httpx for niquests in order to stabilize network I/O

nc_py_api/__init__.py, nc_py_api/_exceptions.py, nc_py_api/ex_app/integration_fastapi.py, tests/_install_init_handler_models.py
* fix `fetch_models_task` fixed for individual files download
* added docs for `fetch_models_task` and model dict in `set_handlers`
* added a custom exception for model download fail since this function can be used independently too
although I'm not too sure of the custom exception, it doesn't serve much purpose except a few pylint ignore comments.
=> fix: fetch_models_task fixed for files and docs added
